import type { Checklist } from './types';

export const INITIAL_CHECKLISTS: Checklist[] = [
  {
    id: 'dr400-1',
    title: 'DR400',
    aircrafts: [
      { id: 'ac-qa', name: 'F-GKQA', url: 'https://www.aero-club-poitou.fr/acp/storage/app/media/Check%20list%20DR400%20QA%20VX%20JFG-06-25.pdf' },
      { id: 'ac-vx', name: 'F-GLVX', url: 'https://www.aero-club-poitou.fr/acp/storage/app/media/Check%20list%20DR400%20QA%20VX%20JFG-06-25.pdf' },
    ],
    sections: [
      {
        id: 'dr400-s-urg',
        title: 'URGENCES',
        items: [
            { id: 'dr400-s-urg-i1', label: 'FEU MOTEUR', action: 'ESSENCE FERMÉE - POMPE ÉLEC COUPÉE - PLEIN GAZ - MIXTURE TIRÉE - CHAUFFAGE/VENTILATION COUPÉE - MAGNÉTOS/BATTERIE/ALT OFF - ATTERRIR IMMÉDIATEMENT', checked: false, isCritical: true },
            { id: 'dr400-s-urg-i2', label: 'PANNE ALTERNATEUR', action: 'ALT OFF PUIS ON. SI PANNE PERSISTE ➜ ALT OFF, DÉLESTER ÉQUIPEMENTS NON INDISPENSABLES. SE POSER DÈS QUE POSSIBLE', checked: false, isCritical: true },
            { id: 'dr400-s-urg-i3', label: 'ATTERRISSAGE D\'URGENCE', action: 'CEINTURES ATTACHÉS, POMPE ÉLEC OFF, MIXTURE TIRÉE, GAZ RÉDUIT, MAGNÉTOS OFF, ESSENCE FERMÉE, ALT OFF, VOLETS SORTIS, BATTERIE OFF. DÉVERROUILLER VERRIÈRE.', checked: false, isCritical: true },
            { id: 'dr400-s-urg-i4', label: 'GIVRAGE CARBURATEUR', action: 'RÉCHAUF CARBU TIRÉE CHAUD - AUGMENTER LA PUISSANCE', checked: false, isCritical: true },
            { id: 'dr400-s-urg-i5', label: 'CHUTE PRESSION HUILE', action: 'VÉRIFIER T° HUILE. SI AUGMENTE ➜ RÉDUIRE PUISSANCE, ATTERRIR IMMÉDIATEMENT', checked: false, isCritical: true },
            { id: 'dr400-s-urg-i6', label: 'VRILLE INVOLONTAIRE', action: 'GAZ ➜ RÉDUIT, PALONNIER ➜ OPPOSÉ, MANCHE ➜ AU NEUTRE', checked: false, isCritical: true },
        ],
      },
      {
          id: 'dr400-s-det',
          title: 'DETRESSE & TRANSPONDEUR',
          items: [
              { id: 'dr400-s-det-i0', label: 'FRÉQUENCE', action: 'Fréquence utilisée ou 121.5 MHz', checked: false },
              { id: 'dr400-s-det-i1', label: 'MAYDAY (DETRESSE)', action: "APPEL: MAYDAYx3, 'indicatif'x3, sur (fréquence). MESSAGE: Position, cap, altitude, vitesse, nature détresse, intentions.", checked: false, isCritical: true },
              { id: 'dr400-s-det-i2', label: 'PAN PAN (URGENCE)', action: "APPEL: PAN PANx3, 'indicatif'x3, sur (fréquence). MESSAGE: Position, cap, altitude, vitesse, nature détresse, intentions.", checked: false, isCritical: true },
              { id: 'dr400-s-det-i3', label: 'CODE 7500', action: 'INTERVENTION ILLICITE', checked: false },
              { id: 'dr400-s-det-i4', label: 'CODE 7600', action: 'PANNE RADIO', checked: false },
              { id: 'dr400-s-det-i5', label: 'CODE 7700', action: 'URGENCE ET DETRESSE', checked: false },
          ],
      },
      {
          id: 'dr400-s-param',
          title: 'PARAMÈTRES AVION (F-GKQA / F-GLVX)',
          items: [
              { id: 'dr400-s-param-i1', label: 'LIMITE VENT DE TRAVERS', action: '22 KT', checked: false },
              { id: 'dr400-s-param-i2', label: 'CARBURANT (100LL)', action: 'QA: 100L utiles (3h20) / VX: 150L utiles (5h00)', checked: false },
              { id: 'dr400-s-param-i3', label: 'MASSE MAX', action: '1000 KG', checked: false },
              { id: 'dr400-s-param-i4', label: 'MASSE À VIDE', action: 'QA: 606 KG / VX: 610 KG', checked: false },
              { id: 'dr400-s-param-i5', label: 'DISTANCES DÉC/ATT', action: 'TODA: 485m (+30%) / LDA: 470m (+30%)', checked: false },
              { id: 'dr400-s-param-i6', label: 'FACTEUR DE BASE', action: '0,54', checked: false },
          ],
      },
      {
          id: 'dr400-s-vit',
          title: 'VITESSES (PRE-AFFICHAGES)',
          items: [
              { id: 'dr400-s-vit-i1', label: 'ROTATION', action: '54 KT', checked: false },
              { id: 'dr400-s-vit-i2', label: 'MONTÉE NORMALE', action: '80 KT', checked: false },
              { id: 'dr400-s-vit-i3', label: 'MONTÉE PENTE MAX', action: '70 KT', checked: false },
              { id: 'dr400-s-vit-i4', label: 'CROISIÈRE (2400 RPM)', action: '111 KT', checked: false },
              { id: 'dr400-s-vit-i5', label: 'VFE (VOLETS)', action: '92 KT', checked: false },
              { id: 'dr400-s-vit-i6', label: 'VNO (AIR TURBULENT)', action: '140 KT', checked: false },
              { id: 'dr400-s-vit-i7', label: 'VNE (À NE JAMAIS DÉPASSER)', action: '166 KT', checked: false },
              { id: 'dr400-s-vit-i8', label: 'APPROCHE PALIER (2000 RPM)', action: '80 KT', checked: false },
              { id: 'dr400-s-vit-i9', label: 'APPROCHE DESCENTE (1600 RPM)', action: '65 KT', checked: false },
              { id: 'dr400-s-vit-i10', label: 'FINALE (1.3 VS0)', action: '65 KT', checked: false },
              { id: 'dr400-s-vit-i11', label: 'VA (MANOEUVRE)', action: '116 KT', checked: false },
              { id: 'dr400-s-vit-i12', label: 'VS (DÉCROCHAGE LISSE)', action: '54 KT', checked: false },
              { id: 'dr400-s-vit-i13', label: 'VS1 (DÉCR. 1 CRAN)', action: '51 KT', checked: false },
              { id: 'dr400-s-vit-i14', label: 'VS0 (DÉCR. 2 CRANS)', action: '47 KT', checked: false },
              { id: 'dr400-s-vit-i15', label: 'FINESSE MAX LISSE', action: '78 KT', checked: false },
              { id: 'dr400-s-vit-i16', label: 'FINESSE MAX EN ÉVOLUTION', action: '80 KT', checked: false },
          ],
      },
      {
          id: 'dr400-s-tdp',
          title: 'TOUR DE PISTE (RÉCAPITULATIF)',
          items: [
              { id: 'dr400-s-tdp-i1', label: 'PRÉPARATION (VENT ARRIÈRE)', action: 'Radio Vent Arrière, Réchauffe carbu CHAUD, Phares ON, RPM 2000, Volets 10°, Compensation', checked: false },
              { id: 'dr400-s-tdp-i2', label: 'APPROCHE DESCENTE', action: 'RPM ~1600, VI ~65kt (120kmh)', checked: false },
              { id: 'dr400-s-tdp-i3', label: 'APPROCHE PALIER', action: 'RPM ~2000, VI ~80kt (150kmh)', checked: false },
              { id: 'dr400-s-tdp-i4', label: 'FINALE', action: 'Radio Finale, Volets à la demande', checked: false },
              { id: 'dr400-s-tdp-i5', label: 'MONTÉE INITIALE', action: 'Plein gaz, VI ~70kt (130kmh)', checked: false },
              { id: 'dr400-s-tdp-i6', label: 'À 300 FT/SOL', action: 'Volets rentrés', checked: false },
              { id: 'dr400-s-tdp-i7', label: 'À 500 FT/SOL', action: 'Pompe OFF, Phare OFF', checked: false },
              { id: 'dr400-s-tdp-i8', label: 'EN CAS DE TOUCH & GO', action: 'Compensateur DÉCO, Volets 10°, Plein gaz, Réchauffe carbu FROID', checked: false },
          ]
      },
      {
        id: 's1',
        title: 'AVANT MISE EN ROUTE',
        items: [
          { id: 's1i1', label: 'INSCRIPTION PLANCHE CLUB', action: 'EFFECTUÉE', checked: false },
          { id: 's1i2', label: 'DOCUMENTS AVION/PILOTE', action: 'VÉRIFIÉS - À BORD', checked: false },
          { id: 's1i3', label: 'MÉTÉO & NOTAM', action: 'VÉRIFIÉS', checked: false },
          { id: 's1i4', label: 'CACHE PITOT & STATIQUE', action: 'ENLEVÉ', checked: false },
          { id: 's1i5', label: 'BARRE DE GUIDAGE', action: 'ENLEVÉE', checked: false },
          { id: 's1i6', label: 'CLEF', action: 'RETIRÉE', checked: false },
          { id: 's1i7', label: 'NIVEAU D\'HUILE', action: 'VÉRIFIÉ', checked: false },
          { id: 's1i8', label: 'ESSENCE', action: 'OUVERT ET ANNONCÉE (QUANTITÉ & AUTONOMIE)', checked: false },
          { id: 's1i9', label: 'VANNE RÉSERVOIR AUXILIAIRE', action: 'POUSSÉE - FERMÉE (SUR F-GLVX SEULEMENT)', checked: false },
          { id: 's1i10', label: 'PURGES', action: 'EFFECTUÉES', checked: false },
          { id: 's1i11', label: 'PRÉ VOL EXTÉRIEURE & INTÉRIEURE', action: 'EFFECTUÉES', checked: false },
          { id: 's1i12', label: 'FEUX (LIGHTS)', action: 'VÉRIFIÉS', checked: false },
          { id: 's1i13', label: 'ALARME DÉCROCHAGE', action: 'TESTÉE', checked: false },
          { id: 's1i14', label: 'CEINTURES', action: 'ATTACHÉES', checked: false },
          { id: 's1i15', label: 'CASQUES', action: 'BRANCHÉS', checked: false },
          { id: 's1i16', label: 'COMMANDES', action: 'LIBRES ET DANS LE BON SENS', checked: false },
          { id: 's1i17', label: 'MASSE ET CENTRAGE', action: 'EFFECTUÉS', checked: false },
          { id: 's1i18', label: 'DISTANCES DÉCOLLAGE /ATTERRISSAGE', action: 'VÉRIFIÉES', checked: false },
          { id: 's1i19', label: 'FUSIBLES', action: 'EN PLACE', checked: false },
          { id: 's1i20', label: 'BRIEFING PASSAGERS', action: 'EFFECTUÉ', checked: false },
        ],
      },
      {
        id: 's2',
        title: 'MISE EN ROUTE',
        items: [
          { id: 's2i1', label: 'VERRIÈRE', action: 'FERMÉE', checked: false },
          { id: 's2i2', label: 'FREINS DE PARC', action: 'SERRÉS', checked: false },
          { id: 's2i3', label: 'MIXTURE', action: 'POUSSÉE - PLEIN RICHE', checked: false },
          { id: 's2i4', label: 'MASTER RADIO', action: 'OFF', checked: false },
          { id: 's2i5', label: 'HORAMÈTRE', action: 'NOTÉ', checked: false },
          { id: 's2i6', label: 'BATTERIE', action: 'ON', checked: false },
          { id: 's2i7', label: 'VOLETS (FLAPS)', action: 'RENTRÉS', checked: false },
          { id: 's2i8', label: 'MOTEUR FROID', action: 'RÉCHAUFFE CARBU - TIRÉE CHAUD', checked: false },
          { id: 's2i9', label: 'MOTEUR CHAUD', action: 'RÉCHAUFFE CARBU - POUSSÉE FROID', checked: false },
          { id: 's2i10', label: 'CLÉ', action: 'EN PLACE - CONTACT SUR BOTH', checked: false },
          { id: 's2i11', label: 'POMPE ÉLECTRIQUE', action: 'ON - PRESSION VÉRIFIÉE', checked: false },
          { id: 's2i12', label: 'INJECTIONS', action: '1 À 4 SELON TEMPÉRATURE MOTEUR', checked: false },
          { id: 's2i13', label: 'GAZ', action: '1 CM MAXI', checked: false },
          { id: 's2i14', label: 'ANTICOLLISION', action: 'ON', checked: false },
          { id: 's2i15', label: 'SÉCURITÉ', action: 'ABORDS DÉGAGÉS', checked: false },
          { id: 's2i16', label: 'DÉMARREUR / START', action: 'ACTIONNÉ - MAX 10 SECONDES', checked: false },
          { id: 's2i17', label: 'RÉGIME', action: '1200 RPM MAX', checked: false },
          { id: 's2i18', label: 'PRESSION HUILE', action: 'VÉRIFIÉE (PLAGE JAUNE/VERTE DANS LES 30 SEC)', checked: false },
        ],
      },
      {
        id: 's3',
        title: 'APRES MISE EN ROUTE',
        items: [
          { id: 's3i1', label: 'RÉCHAUFFE CARBU', action: 'POUSSÉE - FROID', checked: false },
          { id: 's3i2', label: 'RÉGIME', action: '1200 TR/MIN', checked: false },
          { id: 's3i3', label: 'ALTERNATEUR', action: 'ON - DÉBIT OK', checked: false },
          { id: 's3i4', label: 'POMPE ÉLECTRIQUE', action: 'OFF - PRESSION VÉRIFIÉE', checked: false },
          { id: 's3i5', label: 'MASTER RADIO', action: 'ON', checked: false },
          { id: 's3i6', label: 'GYROS', action: 'DÉPRESSION OK (PLAGE VERTE)', checked: false },
          { id: 's3i7', label: 'RADIO + RADIO / NAV', action: 'VÉRIFIÉS ON - FRÉQUENCES & VOLUMES VÉRIFIÉS', checked: false },
          { id: 's3i8', label: 'TRANSPONDEUR', action: 'ALT ET SUR 7000', checked: false },
          { id: 's3i9', label: 'ALTIMÈTRE', action: 'RÉGLÉ À L\'ALTITUDE DU TERRAIN', checked: false },
          { id: 's3i10', label: 'CONSERVATEUR DE CAP', action: 'RÉGLÉ', checked: false },
          { id: 's3i11', label: 'COMPENSATEUR', action: 'VÉRIFIÉ - POSITION DÉCOLLAGE', checked: false },
          { id: 's3i12', label: 'ATIS', action: 'NOTÉ', checked: false },
          { id: 's3i13', label: 'BRIEFING ROULAGE', action: 'EFFECTUÉ', checked: false },
          { id: 's3i14', label: 'PHARE DE ROULAGE', action: 'ON', checked: false },
          { id: 's3i15', label: 'CONTACT RADIO', action: 'POITIERS TOUR DE F-****, BONJOUR !', checked: false },
          { id: 's3i16', label: 'TOP CHRONO', action: 'NOTÉ', checked: false },
        ],
      },
       {
        id: 's4',
        title: 'ROULAGE',
        items: [
            { id: 's4i1', label: 'FREINS', action: 'ESSAYÉS', checked: false },
            { id: 's4i2', label: 'HORIZON ARTIFICIEL', action: 'STABLE', checked: false },
            { id: 's4i3', label: 'CONSERVATEUR DE CAP / COMPAS', action: 'CAPS AUGMENTENT/DIMINUENT/COHÉRENCE', checked: false },
            { id: 's4i4', label: 'BILLE - MAQUETTE', action: 'DANS LE BON SENS', checked: false },
        ],
      },
      {
        id: 's5',
        title: 'AU PARKING - ARRET MOTEUR',
        items: [
          { id: 's5i1', label: 'RÉGIME', action: '1200 TR/MIN', checked: false },
          { id: 's5i2', label: 'FREINS DE PARC', action: 'SERRÉS - SAUF DEVANT LE HANGAR', checked: false },
          { id: 's5i3', label: 'TOP CHRONO', action: 'NOTÉ', checked: false },
          { id: 's5i4', label: 'CONTACT RADIO', action: 'F-**** AU PARKING POUR QUITTER', checked: false },
          { id: 's5i5', label: 'TRANSPONDEUR', action: 'SUR 7000', checked: false },
          { id: 's5i6', label: 'MASTER RADIO', action: 'OFF', checked: false },
          { id: 's5i7', label: 'ALTERNATEUR', action: 'OFF', checked: false },
          { id: 's5i8', label: 'CONTACT MAGNÉTOS', action: '900 TR/MIN - ESSAI COUPURE', checked: false },
          { id: 's5i9', label: 'RÉGIME', action: '1200 TR/MIN', checked: false },
          { id: 's5i10', label: 'MIXTURE', action: 'TIRÉE - PLEIN PAUVRE', checked: false },
          { id: 's5i11', label: 'CONTACT MAGNÉTOS', action: 'OFF - CLEF RETIRÉE', checked: false },
          { id: 's5i12', label: 'PHARES ATTERRISSAGE & ROULAGE', action: 'OFF', checked: false },
          { id: 's5i13', label: 'FEUX DE NAV', action: 'OFF', checked: false },
          { id: 's5i14', label: 'ANTICOLLISION', action: 'LAISSER SUR ON', checked: false },
          { id: 's5i15', label: 'BATTERIE', action: 'OFF', checked: false },
          { id: 's5i16', label: 'VOLETS', action: 'SORTIS - 2 CRANS', checked: false },
          { id: 's5i17', label: 'HORAMÈTRE', action: 'NOTÉ', checked: false },
          { id: 's5i18', label: 'CACHES PITOT & STATIQUES', action: 'PITOT', checked: false },
          { id: 's5i19', label: 'AVION', action: 'A LAVER', checked: false },
          { id: 's5i20', label: 'DOCUMENTS', action: 'A REMPLIR', checked: false },
        ]
      }
    ],
  },
  {
    id: 'c150-1',
    title: 'C150 / C152',
    aircrafts: [
        { id: 'ac-bk', name: 'F-BUBK', url: 'https://www.aero-club-poitou.fr/acp/storage/app/media/Check%20list%20C150%20BK%20JFG-06-25.pdf' },
        { id: 'ac-ya', name: 'F-GIYA', url: 'https://www.aero-club-poitou.fr/acp/storage/app/media/Check%20list%20C150%20YA%20JFG-06-25.pdf' }
    ],
    sections: [
      {
        id: 'c152-s-urg',
        title: 'URGENCES',
        items: [
            { id: 'c152-s-urg-i1', label: 'FEU MOTEUR', action: 'ESSENCE FERMÉE - PLEIN GAZ - MIXTURE TIRÉE - CHAUFFAGE/VENTILATION COUPÉS - MAGNÉTOS/BATTERIE/ALT OFF - ATTERRIR IMMÉDIATEMENT', checked: false, isCritical: true },
            { id: 'c152-s-urg-i2', label: 'PANNE ALTERNATEUR', action: 'ALT OFF PUIS ON. SI PANNE PERSISTE ➜ ALT OFF, DÉLESTER ÉQUIPEMENTS NON INDISPENSABLES. SE POSER DÈS QUE POSSIBLE', checked: false, isCritical: true },
            { id: 'c152-s-urg-i3', label: 'ATTERRISSAGE D\'URGENCE', action: 'CEINTURES ATTACHÉS, MIXTURE TIRÉE, GAZ RÉDUIT, MAGNÉTOS OFF, ESSENCE FERMÉE, ALT OFF, VOLETS SORTIS, BATTERIE OFF. DÉVERROUILLER PORTES.', checked: false, isCritical: true },
            { id: 'c152-s-urg-i4', label: 'GIVRAGE CARBURATEUR', action: 'RÉCHAUF CARBU TIRÉE CHAUD - AUGMENTER LA PUISSANCE', checked: false, isCritical: true },
            { id: 'c152-s-urg-i5', label: 'CHUTE PRESSION HUILE', action: 'VÉRIFIER T° HUILE. SI AUGMENTE ➜ RÉDUIRE PUISSANCE, ATTERRIR IMMÉDIATEMENT', checked: false, isCritical: true },
            { id: 'c152-s-urg-i6', label: 'VRILLE INVOLONTAIRE', action: 'GAZ ➜ RÉDUIT, PALONNIER ➜ OPPOSÉ, MANCHE ➜ AU NEUTRE', checked: false, isCritical: true },
        ],
      },
      {
          id: 'c152-s-det',
          title: 'DETRESSE & TRANSPONDEUR',
          items: [
              { id: 'c152-s-det-i0', label: 'FRÉQUENCE', action: 'Fréquence utilisée ou 121.5 MHz', checked: false },
              { id: 'c152-s-det-i1', label: 'MAYDAY (DETRESSE)', action: "APPEL: MAYDAYx3, 'indicatif'x3, sur (fréquence). MESSAGE: Position, heure, cap, altitude, vitesse, nature détresse.", checked: false, isCritical: true },
              { id: 'c152-s-det-i2', label: 'PAN PAN (URGENCE)', action: "APPEL: PAN PANx3, 'indicatif'x3, sur (fréquence). MESSAGE: Position, heure, cap, altitude, vitesse, nature détresse.", checked: false, isCritical: true },
              { id: 'c152-s-det-i3', label: 'CODE 7000', action: 'VFR', checked: false },
              { id: 'c152-s-det-i4', label: 'CODE 7500', action: 'INTERVENTION ILLICITE', checked: false },
              { id: 'c152-s-det-i5', label: 'CODE 7600', action: 'PANNE RADIO', checked: false },
              { id: 'c152-s-det-i6', label: 'CODE 7700', action: 'URGENCE ET DETRESSE', checked: false },
          ],
      },
      {
          id: 'c152-s-param',
          title: 'PARAMÈTRES AVION (F-GIYA)',
          items: [
              { id: 'c152-s-param-i1', label: 'LIMITE VENT DE TRAVERS', action: '12 KT', checked: false },
              { id: 'c152-s-param-i2', label: 'CARBURANT (100LL)', action: '92L utiles (4h00)', checked: false },
              { id: 'c152-s-param-i3', label: 'MASSE MAX', action: '758 KG', checked: false },
              { id: 'c152-s-param-i4', label: 'MASSE À VIDE', action: '540 KG', checked: false },
              { id: 'c152-s-param-i5', label: 'DISTANCES DÉC/ATT', action: 'TODA: 408m (+30%) / LDA: 366m (+30%)', checked: false },
              { id: 'c152-s-param-i6', label: 'FACTEUR DE BASE', action: '0,60', checked: false },
          ],
      },
      {
          id: 'c152-s-vit',
          title: 'VITESSES (PRE-AFFICHAGES)',
          items: [
              { id: 'c152-s-vit-i1', label: 'ROTATION', action: '50 KT', checked: false },
              { id: 'c152-s-vit-i2', label: 'MONTÉE NORMALE', action: '70 KT', checked: false },
              { id: 'c152-s-vit-i3', label: 'MONTÉE PENTE MAX', action: '60 KT', checked: false },
              { id: 'c152-s-vit-i4', label: 'CROISIÈRE (2400 RPM)', action: '101 KT', checked: false },
              { id: 'c152-s-vit-i5', label: 'VFE (VOLETS)', action: '85 KT', checked: false },
              { id: 'c152-s-vit-i6', label: 'VNO (AIR TURBULENT)', action: '111 KT', checked: false },
              { id: 'c152-s-vit-i7', label: 'VNE (À NE JAMAIS DÉPASSER)', action: '149 KT', checked: false },
              { id: 'c152-s-vit-i8', label: 'APPROCHE PALIER (2000 RPM)', action: '70 KT', checked: false },
              { id: 'c152-s-vit-i9', label: 'APPROCHE DESCENTE (1600 RPM)', action: '61 KT', checked: false },
              { id: 'c152-s-vit-i10', label: 'FINALE (1.3 VS0)', action: '55 KT', checked: false },
              { id: 'c152-s-vit-i11', label: 'VA (MANOEUVRE)', action: '104 KT', checked: false },
              { id: 'c152-s-vit-i12', label: 'VS (DÉCROCHAGE LISSE)', action: '40 KT', checked: false },
              { id: 'c152-s-vit-i13', label: 'VS1 (DÉCR. 10°)', action: '40 KT', checked: false },
              { id: 'c152-s-vit-i14', label: 'VS1 (DÉCR. 20°)', action: '40 KT', checked: false },
              { id: 'c152-s-vit-i15', label: 'VS0 (DÉCR. 30°)', action: '35 KT', checked: false },
              { id: 'c152-s-vit-i16', label: 'FINESSE MAX LISSE', action: '60 KT', checked: false },
              { id: 'c152-s-vit-i17', label: 'FINESSE MAX EN ÉVOLUTION', action: '70 KT', checked: false },
          ],
      },
      {
          id: 'c152-s-tdp',
          title: 'TOUR DE PISTE (RÉCAPITULATIF)',
          items: [
              { id: 'c152-s-tdp-i1', label: 'PRÉPARATION (VENT ARRIÈRE)', action: 'Radio Vent Arrière, Réchauffe carbu CHAUD, Phares ON, RPM 2000, Volets 10°, Compensation', checked: false },
              { id: 'c152-s-tdp-i2', label: 'APPROCHE DESCENTE', action: 'VI ~61kt', checked: false },
              { id: 'c152-s-tdp-i3', label: 'APPROCHE PALIER', action: 'RPM adapté, VI ~70kt', checked: false },
              { id: 'c152-s-tdp-i4', label: 'FINALE', action: 'Radio Finale, Volets à la demande', checked: false },
              { id: 'c152-s-tdp-i5', label: 'MONTÉE INITIALE', action: 'Plein gaz, VI ~70kt', checked: false },
              { id: 'c152-s-tdp-i6', label: 'À 300 FT/SOL', action: 'Volets rentrés', checked: false },
              { id: 'c152-s-tdp-i7', label: 'À 500 FT/SOL', action: 'Phare OFF', checked: false },
              { id: 'c152-s-tdp-i8', label: 'EN CAS DE TOUCH & GO', action: 'Compensateur DÉCO, Volets 10°, Plein gaz, Réchauffe carbu FROID', checked: false },
          ]
      },
      {
        id: 'c150-s1',
        title: 'AVANT MISE EN ROUTE',
        items: [
          { id: 'c150-s1i1', label: 'INSCRIPTION PLANCHE CLUB', action: 'EFFECTUÉE', checked: false },
          { id: 'c150-s1i2', label: 'DOCUMENTS AVION/PILOTE', action: 'VÉRIFIÉS - À BORD', checked: false },
          { id: 'c150-s1i3', label: 'MÉTÉO & NOTAM', action: 'VÉRIFIÉS', checked: false },
          { id: 'c150-s1i4', label: 'CACHE PITOT', action: 'ENLEVÉ', checked: false },
          { id: 'c150-s1i5', label: 'BARRE DE GUIDAGE', action: 'ENLEVÉE', checked: false },
          { id: 'c150-s1i6', label: 'CLEF', action: 'RETIRÉE', checked: false },
          { id: 'c150-s1i7', label: 'NIVEAU D\'HUILE', action: 'VÉRIFIÉ', checked: false },
          { id: 'c150-s1i8', label: 'ESSENCE', action: 'OUVERT ET ANNONCÉE (QUANTITÉ & AUTONOMIE)', checked: false },
          { id: 'c150-s1i9', label: 'PURGES', action: 'EFFECTUÉES', checked: false },
          { id: 'c150-s1i10', label: 'PRÉ VOL EXTÉRIEURE & INTÉRIEURE', action: 'EFFECTUÉES', checked: false },
          { id: 'c150-s1i11', label: 'FEUX (LIGHTS)', action: 'VÉRIFIÉS', checked: false },
          { id: 'c150-s1i12', label: 'ALARME DÉCROCHAGE', action: 'TESTÉE', checked: false },
          { id: 'c150-s1i13', label: 'CEINTURES', action: 'ATTACHÉES', checked: false },
          { id: 'c150-s1i14', label: 'CASQUES', action: 'BRANCHÉS', checked: false },
          { id: 'c150-s1i15', label: 'COMMANDES', action: 'LIBRES ET DANS LE BON SENS', checked: false },
          { id: 'c150-s1i16', label: 'MASSE ET CENTRAGE', action: 'EFFECTUÉS', checked: false },
          { id: 'c150-s1i17', label: 'DISTANCES DÉCOLLAGE /ATTERRISSAGE', action: 'VÉRIFIÉES', checked: false },
          { id: 'c150-s1i18', label: 'FUSIBLES', action: 'EN PLACE', checked: false },
          { id: 'c150-s1i19', label: 'BRIEFING PASSAGERS', action: 'EFFECTUÉ', checked: false },
        ],
      },
      {
        id: 'c150-s2',
        title: 'MISE EN ROUTE',
        items: [
          { id: 'c150-s2i1', label: 'PORTES', action: 'FERMÉES', checked: false },
          { id: 'c150-s2i2', label: 'FREINS', action: 'SERRÉS - PIEDS SUR LES FREINS', checked: false },
          { id: 'c150-s2i3', label: 'MIXTURE', action: 'POUSSÉE - PLEIN RICHE', checked: false },
          { id: 'c150-s2i4', label: 'HORAMÈTRE', action: 'NOTÉ', checked: false },
          { id: 'c150-s2i5', label: 'RADIO + RADIO / Nav', action: 'OFF', checked: false },
          { id: 'c150-s2i6', label: 'BATTERIE', action: 'ON', checked: false },
          { id: 'c150-s2i7', label: 'VOLETS (FLAPS)', action: 'RENTRÉS', checked: false },
          { id: 'c150-s2i8', label: 'MOTEUR FROID', action: 'RÉCHAUFFE CARBU - TIRÉE CHAUD', checked: false },
          { id: 'c150-s2i9', label: 'MOTEUR CHAUD', action: 'RÉCHAUFFE CARBU - POUSSÉE FROID', checked: false },
          { id: 'c150-s2i10', label: 'CLÉ', action: 'EN PLACE - CONTACT SUR BOTH', checked: false },
          { id: 'c150-s2i11', label: 'INJECTIONS', action: '1er vol: 1-4 / Hiver: 8+10mn / Été: 4', checked: false },
          { id: 'c150-s2i12', label: 'GAZ', action: '1 CM MAXI', checked: false },
          { id: 'c150-s2i13', label: 'BEACON', action: 'ON', checked: false },
          { id: 'c150-s2i14', label: 'SÉCURITÉ', action: 'ABORDS DÉGAGÉS', checked: false },
          { id: 'c150-s2i15', label: 'DÉMARREUR / START', action: 'ACTIONNÉ - MAX 10 SECONDES', checked: false },
          { id: 'c150-s2i16', label: 'RÉGIME', action: '1200 RPM MAX', checked: false },
          { id: 'c150-s2i17', label: 'PRESSION HUILE', action: 'VÉRIFIÉE (PLAGE JAUNE/VERTE DANS LES 30 SEC)', checked: false },
        ]
      },
      {
        id: 'c150-s3',
        title: 'APRES MISE EN ROUTE',
        items: [
          { id: 'c150-s3i1', label: 'RECHAUFFE CARBU', action: 'POUSSÉE - FROID', checked: false },
          { id: 'c150-s3i2', label: 'RÉGIME', action: '1200 TR/MIN', checked: false },
          { id: 'c150-s3i3', label: 'ALTERNATEUR', action: 'ON - VOYANT ÉTEINT', checked: false },
          { id: 'c150-s3i4', label: 'GYROS', action: 'DÉPRESSION OK (PLAGE VERTE)', checked: false },
          { id: 'c150-s3i5', label: 'RADIO + RADIO / Nav', action: 'ON - FRÉQUENCES & VOLUMES VÉRIFIÉS', checked: false },
          { id: 'c150-s3i6', label: 'TRANSPONDEUR', action: 'ALT ET SUR 7000', checked: false },
          { id: 'c150-s3i7', label: 'ALTIMÈTRE', action: 'RÉGLÉ À L\'ALTITUDE DU TERRAIN', checked: false },
          { id: 'c150-s3i8', label: 'CONSERVATEUR DE CAP', action: 'RÉGLÉ', checked: false },
          { id: 'c150-s3i9', label: 'COMPENSATEUR', action: 'VÉRIFIÉ - POSITION DÉCOLLAGE', checked: false },
          { id: 'c150-s3i10', label: 'ATIS', action: 'NOTÉ', checked: false },
          { id: 'c150-s3i11', label: 'BRIEFING ROULAGE', action: 'EFFECTUÉ', checked: false },
          { id: 'c150-s3i12', label: 'PHARE', action: 'ON', checked: false },
          { id: 'c150-s3i13', label: 'CONTACT RADIO', action: 'POITIERS TOUR DE F-GIYA, BONJOUR !', checked: false },
          { id: 'c150-s3i14', label: 'TOP CHRONO', action: 'NOTÉ', checked: false },
        ]
      },
      {
        id: 'c150-s4',
        title: 'ROULAGE',
        items: [
          { id: 'c150-s4i1', label: 'FREINS', action: 'ESSAYÉS', checked: false },
          { id: 'c150-s4i2', label: 'HORIZON ARTIFICIEL', action: 'STABLE', checked: false },
          { id: 'c150-s4i3', label: 'CONSERVATEUR DE CAP / COMPAS', action: 'CAPS AUGMENTENT/DIMINUENT/COHÉRENCE', checked: false },
          { id: 'c150-s4i4', label: 'BILLE - MAQUETTE', action: 'DANS LE BON SENS', checked: false },
        ]
      },
      {
        id: 'c150-s5',
        title: 'AU POINT D\'ATTENTE',
        items: [
          { id: 'c150-s5i1', label: 'FREINS', action: 'SERRÉS - PIEDS SUR LES FREINS', checked: false },
          { id: 'c150-s5i2', label: 'RÉGIME', action: '1200 TR/MIN', checked: false },
          { id: 'c150-s5i3', label: 'PHARE', action: 'OFF', checked: false },
          { id: 'c150-s5i4', label: 'TEMPÉRATURE D\'HUILE', action: 'SUFFISANTE', checked: false },
          { id: 'c150-s5i5', label: 'RÉCHAUFFE CARBU', action: 'POUSSÉE - FROID', checked: false },
          { id: 'c150-s5i6', label: 'RÉGIME', action: '1800 TR/MIN', checked: false },
          { id: 'c150-s5i7', label: 'SÉLECTION MAGNÉTOS', action: 'PERTE < 150 / ÉCART R-L < 75 TR/MIN', checked: false },
          { id: 'c150-s5i8', label: 'RECHAUFFE CARBU', action: 'ESSAI (PERTE < 200 TR/MIN)', checked: false },
          { id: 'c150-s5i9', label: 'RALENTI', action: 'MOTEUR NE CALE PAS (600 - 700 TR/MIN)', checked: false },
          { id: 'c150-s5i10', label: 'RÉGIME', action: '1200 TR/MIN', checked: false },
        ]
      },
      {
        id: 'c150-s6',
        title: 'AVANT ALIGNEMENT',
        items: [
          { id: 'c150-s6i1', label: 'BATTERIE', action: 'ON', checked: false },
          { id: 'c150-s6i2', label: 'ALTERNATEUR', action: 'ON - VOYANT ÉTEINT', checked: false },
          { id: 'c150-s6i3', label: 'CONTACT MAGNÉTOS', action: 'SUR BOTH', checked: false },
          { id: 'c150-s6i4', label: 'RÉCHAUFFE CARBU', action: 'POUSSÉE - FROID', checked: false },
          { id: 'c150-s6i5', label: 'MIXTURE', action: 'POUSSÉE - PLEIN RICHE', checked: false },
          { id: 'c150-s6i6', label: 'ESSENCE', action: 'ROBINET OUVERT', checked: false },
          { id: 'c150-s6i7', label: 'HUILE', action: 'PRESSION/TEMPÉRATURE PLAGE VERTE', checked: false },
          { id: 'c150-s6i8', label: 'VOLETS (FLAPS)', action: 'ESSAYÉS - POSITION DÉCOLLAGE (10°)', checked: false },
          { id: 'c150-s6i9', label: 'HORIZON ARTIFICIEL', action: 'RÉGLÉ', checked: false },
          { id: 'c150-s6i10', label: 'BILLE - MAQUETTE', action: 'Ok', checked: false },
          { id: 'c150-s6i11', label: 'CONSERVATEUR DE CAP', action: 'RÉGLÉ', checked: false },
          { id: 'c150-s6i12', label: 'VARIOMÈTRE', action: 'Ok', checked: false },
          { id: 'c150-s6i13', label: 'PORTES', action: 'FERMÉES', checked: false },
          { id: 'c150-s6i14', label: 'CEINTURES & HARNAIS', action: 'ATTACHÉS', checked: false },
          { id: 'c150-s6i15', label: 'ALTIMÈTRE', action: 'AU QNH', checked: false },
          { id: 'c150-s6i16', label: 'PHARE', action: 'ON', checked: false },
          { id: 'c150-s6i17', label: 'COMMANDES', action: 'LIBRES - PAS DE POINT DUR', checked: false },
          { id: 'c150-s6i18', label: 'BRIEFING PANNE AU DÉCOLLAGE', action: 'EFFECTUÉ', checked: false },
          { id: 'c150-s6i19', label: 'BRIEFING DÉPART', action: 'EFFECTUÉ', checked: false },
          { id: 'c150-s6i20', label: 'CONTACT RADIO', action: 'PRÊT AU POINT D\'ATTENTE', checked: false },
        ]
      },
      {
        id: 'c150-s7',
        title: 'ALIGNEMENT / DECOLLAGE',
        items: [
          { id: 'c150-s7i1', label: 'CONSERVATEUR DE CAP ET COMPAS', action: 'VÉRIFIÉS / QFU', checked: false },
          { id: 'c150-s7i2', label: 'PUISSANCE MINI ANNONCÉE', action: '2150 TR/MIN', checked: false },
          { id: 'c150-s7i3', label: 'TOP CHRONO', action: 'NOTÉ', checked: false },
          { id: 'c150-s7i4', label: 'ROTATION', action: 'VI = 50 KTS', checked: false },
          { id: 'c150-s7i5', label: '300 Ft / SOL', action: 'VOLETS RENTRÉS', checked: false },
          { id: 'c150-s7i6', label: 'MONTÉE', action: 'VI = 70 KTS', checked: false },
          { id: 'c150-s7i7', label: '500 Ft / SOL', action: 'PHARE OFF', checked: false },
        ]
      },
      {
        id: 'c150-s8',
        title: 'VENT ARRIERE',
        items: [
          { id: 'c150-s8i1', label: 'RÉCHAUFFE CARBU', action: 'TIRÉE - CHAUD', checked: false },
          { id: 'c150-s8i2', label: 'MIXTURE', action: 'POUSSÉE - PLEIN RICHE', checked: false },
          { id: 'c150-s8i3', label: 'PHARE', action: 'ON', checked: false },
          { id: 'c150-s8i4', label: 'VOLETS', action: 'SORTIS 10° (ARC BLANC)', checked: false },
        ]
      },
      {
        id: 'c150-s9',
        title: 'FINALE',
        items: [
          { id: 'c150-s9i1', label: 'REMISE DE GAZ', action: 'ENVISAGÉE', checked: false },
          { id: 'c150-s9i2', label: 'VOLETS', action: 'A LA DEMANDE', checked: false },
          { id: 'c150-s9i3', label: 'AXE - PLAN - VITESSE - CONFIGURATION', action: 'AUTORISÉ(e) OU PISTE LIBRE', checked: false },
        ]
      },
      {
        id: 'c150-s10',
        title: 'REMISE DES GAZ',
        items: [
          { id: 'c150-s10i1', label: 'ASSIETTE', action: '1/2 ASSIETTE DE MONTÉE - VZ POSITIF', checked: false },
          { id: 'c150-s10i2', label: 'RÉGIME', action: 'PLEINE PUISSANCE', checked: false },
          { id: 'c150-s10i3', label: 'RÉCHAUFFE CARBU', action: 'POUSSÉE - FROID', checked: false },
          { id: 'c150-s10i4', label: 'VOLETS', action: 'RENTRÉS PROGRESSIVEMENT (10°)', checked: false },
        ]
      },
      {
        id: 'c150-s11',
        title: 'APRES ATTERRISSAGE - PISTE DÉGAGÉE',
        items: [
          { id: 'c150-s11i1', label: 'RÉGIME', action: '1200 TR/MIN', checked: false },
          { id: 'c150-s11i2', label: 'RÉCHAUFFE CARBU', action: 'POUSSÉE - FROID', checked: false },
          { id: 'c150-s11i3', label: 'COMPENSATEUR', action: 'AU NEUTRE', checked: false },
          { id: 'c150-s11i4', label: 'VOLETS', action: 'RENTRÉS', checked: false },
        ]
      },
      {
        id: 'c150-s12',
        title: 'AU PARKING-ARRET MOTEUR',
        items: [
          { id: 'c150-s12i1', label: 'RÉGIME', action: '1200 TR/MIN', checked: false },
          { id: 'c150-s12i2', label: 'FREINS', action: 'SERRÉS - PIEDS SUR LES FREINS', checked: false },
          { id: 'c150-s12i3', label: 'TOP CHRONO', action: 'NOTÉ', checked: false },
          { id: 'c150-s12i4', label: 'CONTACT RADIO', action: 'F-GIYA AU PARKING POUR QUITTER', checked: false },
          { id: 'c150-s12i5', label: 'TRANSPONDEUR', action: 'SUR 7000 PUIS SUR OFF', checked: false },
          { id: 'c150-s12i6', label: 'RADIO + RADIO / Nav', action: 'OFF', checked: false },
          { id: 'c150-s12i7', label: 'ALTERNATEUR', action: 'OFF', checked: false },
          { id: 'c150-s12i8', label: 'CONTACT MAGNÉTOS', action: '900 TR/MIN - ESSAI COUPURE', checked: false },
          { id: 'c150-s12i9', label: 'RÉGIME', action: '1200 TR/MIN', checked: false },
          { id: 'c150-s12i10', label: 'MIXTURE', action: 'TIRÉE - PLEIN PAUVRE', checked: false },
          { id: 'c150-s12i11', label: 'CONTACT MAGNÉTOS', action: 'OFF - CLEF RETIRÉE', checked: false },
          { id: 'c150-s12i12', label: 'PHARE', action: 'OFF', checked: false },
          { id: 'c150-s12i13', label: 'FEUX DE NAV', action: 'OFF', checked: false },
          { id: 'c150-s12i14', label: 'BEACON (ANTICOLLISION)', action: 'LAISSER SUR ON', checked: false },
          { id: 'c150-s12i15', label: 'BATTERIE', action: 'OFF', checked: false },
          { id: 'c150-s12i16', label: 'HORAMÈTRE', action: 'NOTÉ', checked: false },
          { id: 'c150-s12i17', label: 'CACHES', action: 'PITOT', checked: false },
          { id: 'c150-s12i18', label: 'AVION', action: 'A LAVER', checked: false },
          { id: 'c150-s12i19', label: 'DOCUMENTS', action: 'A REMPLIR', checked: false },
          { id: 'c150-s12i20', label: 'NOTE', action: 'NE JAMAIS METTRE LA BARRE DE GUIDAGE SUR LA ROUE AVANT (SAUF DANS LE HANGAR)', checked: false },
        ]
      },
    ],
  },
  {
    id: 'evektor-1',
    title: 'EVEKTOR',
    aircrafts: [
        { id: 'ac-pl', name: 'F-HPPL', url: 'https://www.aero-club-poitou.fr/acp/storage/app/media/Check%20list%20EVEKTOR%20PL%20JFG-06-25.pdf' },
        { id: 'ac-ny', name: 'F-HNNY', url: 'https://www.aero-club-poitou.fr/acp/storage/app/media/Check%20list%20EVEKTOR%20NY%20JFG-05-06-25.pdf' },
        { id: 'ac-pi', name: 'F-HMPI', url: 'https://www.aero-club-poitou.fr/acp/storage/app/media/Check%20list%20EVEKTOR%20PI%20JFG-05-06-25.pdf' }
    ],
    sections: [
      {
        id: 'evektor-s-urg',
        title: 'URGENCES',
        items: [
            { id: 'evektor-s-urg-i1', label: 'FEU MOTEUR', action: 'ESSENCE OFF - PLEIN GAZ - CHAUFFAGE/VENTILATION FERMÉS - MAGNÉTOS/MASTER SWITCH OFF - ATTERRIR IMMÉDIATEMENT', checked: false, isCritical: true },
            { id: 'evektor-s-urg-i2', label: 'DESCENTE D\'URGENCE', action: 'PUISSANCE ➜ TOUT RÉDUIT, VOLETS ➜ RENTRÉS 0°, VITESSE ➜ MAX (VNE = 146 KTS)', checked: false, isCritical: true },
            { id: 'evektor-s-urg-i3', label: 'ATTERRISSAGE D\'URGENCE', action: 'MOTEUR ARRÊTÉ: VITESSE 59KT, AIRE D\'ATTERRISSAGE À CHOISIR, HARNAIS ATTACHÉS, VOLETS 30°/50°, MAGNÉTOS/ESSENCE/MASTER OFF', checked: false, isCritical: true },
            { id: 'evektor-s-urg-i4', label: 'GIVRAGE CARBURATEUR', action: 'RÉCHAUF CARBU TIRÉE CHAUD - METTRE AU RALENTI PUIS PUISSANCE NORMALE', checked: false, isCritical: true },
            { id: 'evektor-s-urg-i5', label: 'VRILLE INVOLONTAIRE', action: 'VOLETS ➜ RENTRÉS 0°, PUISSANCE ➜ TOUT RÉDUIT, MANCHE ➜ AU NEUTRE, PALONNIERS ➜ À FOND OPPOSÉ', checked: false, isCritical: true },
        ],
      },
      {
          id: 'evektor-s-det',
          title: 'DETRESSE & TRANSPONDEUR',
          items: [
              { id: 'evektor-s-det-i0', label: 'FRÉQUENCE', action: 'Fréquence utilisée ou 121.5 MHz', checked: false },
              { id: 'evektor-s-det-i1', label: 'MAYDAY (DETRESSE)', action: "APPEL: MAYDAYx3, 'indicatif'x3. MESSAGE: Position, heure, cap, altitude, vitesse, nature détresse...", checked: false, isCritical: true },
              { id: 'evektor-s-det-i2', label: 'PAN PAN (URGENCE)', action: "APPEL: PAN PANx3, 'indicatif'x3. MESSAGE: Position, heure, cap, altitude, vitesse, nature détresse...", checked: false, isCritical: true },
              { id: 'evektor-s-det-i3', label: 'CODE 7000', action: 'VFR', checked: false },
              { id: 'evektor-s-det-i4', label: 'CODE 7500', action: 'INTERVENTION ILLICITE', checked: false },
              { id: 'evektor-s-det-i5', label: 'CODE 7600', action: 'PANNE RADIO', checked: false },
              { id: 'evektor-s-det-i6', label: 'CODE 7700', action: 'URGENCE ET DETRESSE', checked: false },
          ],
      },
      {
          id: 'evektor-s-param',
          title: 'PARAMÈTRES AVION (F-HNNY)',
          items: [
              { id: 'evektor-s-param-i1', label: 'LIMITE VENT', action: 'TRAVERS: 18 KT / ARRIÈRE: 6 KT', checked: false },
              { id: 'evektor-s-param-i2', label: 'CARBURANT (SP98/100LL)', action: '118L utiles (5h54)', checked: false },
              { id: 'evektor-s-param-i3', label: 'MASSE MAX / À VIDE', action: '600 KG / 347 KG', checked: false },
              { id: 'evektor-s-param-i4', label: 'DISTANCES DÉC/ATT', action: 'TODA: 365m (+30%) / LDA: 428m (+30%)', checked: false },
              { id: 'evektor-s-param-i5', label: 'FACTEUR DE BASE', action: '0,60', checked: false },
          ],
      },
      {
          id: 'evektor-s-vit',
          title: 'VITESSES (PRE-AFFICHAGES)',
          items: [
              { id: 'evektor-s-vit-i1', label: 'ROTATION', action: '50 KT (Volets 15°)', checked: false },
              { id: 'evektor-s-vit-i2', label: 'MONTÉE INITIALE', action: '60 KT (Volets 15°)', checked: false },
              { id: 'evektor-s-vit-i3', label: 'MONTÉE NORMALE / Vz MAX', action: '65 KT (Volets 0°)', checked: false },
              { id: 'evektor-s-vit-i4', label: 'MONTÉE PENTE MAX', action: '48 KT (Volets 15°)', checked: false },
              { id: 'evektor-s-vit-i5', label: 'CROISIÈRE 75% (5000 RPM)', action: '95 KT (Volets 0°)', checked: false },
              { id: 'evektor-s-vit-i6', label: 'VFE (VOLETS)', action: '70 KT', checked: false },
              { id: 'evektor-s-vit-i7', label: 'APPROCHE PALIER (4100 RPM)', action: '65-70 KT (Volets 15°)', checked: false },
              { id: 'evektor-s-vit-i8', label: 'APPROCHE DESCENTE (3200 RPM)', action: '65 KT (Volets 15°)', checked: false },
              { id: 'evektor-s-vit-i9', label: 'FINALE (RPM / VOLETS)', action: '60 (0°), 57 (15°), 55 (30°), 52 (50°)', checked: false },
              { id: 'evektor-s-vit-i10', label: 'VS / VS1 / VS0', action: '42 / 41 / 39 KT', checked: false },
              { id: 'evektor-s-vit-i11', label: 'FINESSE MAX LISSE / 15°', action: '59 KT / 57 KT', checked: false },
              { id: 'evektor-s-vit-i12', label: 'PAS DE VITESSE D\'ATTENTE', action: '', checked: false, isCritical: true },
          ],
      },
      {
          id: 'evektor-s-tdp',
          title: 'TOUR DE PISTE (RÉCAPITULATIF)',
          items: [
              { id: 'evektor-s-tdp-i1', label: 'PRÉPARATION (VENT ARRIÈRE)', action: 'Radio Vent Arrière, Réchauffe carbu CHAUD, Phares ON, RPM 4100, Volets 15°, Compensation', checked: false },
              { id: 'evektor-s-tdp-i2', label: 'APPROCHE DESCENTE', action: 'RPM ~3500, VI ~57kt + kVc', checked: false },
              { id: 'evektor-s-tdp-i3', label: 'APPROCHE PALIER', action: 'RPM ~4100, VI ~65 à 70kt', checked: false },
              { id: 'evektor-s-tdp-i4', label: 'FINALE', action: 'Radio Finale, Volets à la demande', checked: false },
              { id: 'evektor-s-tdp-i5', label: 'MONTÉE INITIALE', action: 'Plein gaz, VI ~60kt', checked: false },
              { id: 'evektor-s-tdp-i6', label: 'À 300 FT/SOL', action: 'Volets rentrés', checked: false },
              { id: 'evektor-s-tdp-i7', label: 'À 500 FT/SOL', action: 'Pompe OFF, Phare OFF', checked: false },
              { id: 'evektor-s-tdp-i8', label: 'EN CAS DE TOUCH & GO', action: 'Compensateur DÉCO, Volets 15°, Plein gaz, Réchauffe carbu FROID', checked: false },
          ]
      },
      {
        id: 'evektor-s1',
        title: 'AVANT MISE EN ROUTE',
        items: [
          { id: 'evektor-s1i1', label: 'INSCRIPTION PLANCHE CLUB', action: 'EFFECTUÉE', checked: false },
          { id: 'evektor-s1i2', label: 'DOCUMENTS AVION/PILOTE', action: 'VÉRIFIÉS - À BORD', checked: false },
          { id: 'evektor-s1i3', label: 'MÉTÉO & NOTAM', action: 'VÉRIFIÉS', checked: false },
          { id: 'evektor-s1i4', label: 'CACHE PITOT', action: 'ENLEVÉ', checked: false },
          { id: 'evektor-s1i5', label: 'BARRE DE GUIDAGE', action: 'ENLEVÉE', checked: false },
          { id: 'evektor-s1i6', label: 'CLEF', action: 'RETIRÉE', checked: false },
          { id: 'evektor-s1i7', label: 'NIV. HUILE / LIQUI REFROID', action: 'VÉRIFIÉS', checked: false },
          { id: 'evektor-s1i8', label: 'ESSENCE', action: 'ANNONCÉE (QUANTITÉ & AUTONOMIE)', checked: false },
          { id: 'evektor-s1i9', label: 'PURGES', action: 'EFFECTUÉES', checked: false },
          { id: 'evektor-s1i10', label: 'PRÉ VOL EXTÉRIEURE & INTÉRIEURE', action: 'EFFECTUÉES', checked: false },
          { id: 'evektor-s1i11', label: 'FEUX (LIGHTS)', action: 'VÉRIFIÉS', checked: false },
          { id: 'evektor-s1i12', label: 'ALARME DÉCROCHAGE', action: 'TESTÉE', checked: false },
          { id: 'evektor-s1i13', label: 'HARNAIS - PALONNIERS', action: 'RÉGLÉS - VERROUILLÉS', checked: false },
          { id: 'evektor-s1i14', label: 'CASQUES', action: 'BRANCHÉS', checked: false },
          { id: 'evektor-s1i15', label: 'COMMANDES', action: 'LIBRES ET DANS LE BON SENS', checked: false },
          { id: 'evektor-s1i16', label: 'MASSE ET CENTRAGE', action: 'VÉRIFIÉES', checked: false },
          { id: 'evektor-s1i17', label: 'DISTANCES DÉCOLLAGE /ATTERRISSAGE', action: 'VÉRIFIÉES', checked: false },
          { id: 'evektor-s1i18', label: 'BRIEFING PASSAGERS', action: 'EFFECTUÉ', checked: false },
        ],
      },
      {
        id: 'evektor-s2',
        title: 'MISE EN ROUTE',
        items: [
            { id: 'evektor-s2i1', label: 'VERRIÈRE', action: 'VÉRIFIÉE FERMÉE (2 CLICS)', checked: false },
            { id: 'evektor-s2i2', label: 'BATT G3X', action: 'ON (ATTENDRE AFFICHAGE « GARMIN »)', checked: false },
            { id: 'evektor-s2i3', label: 'MASTER SWITCH (BATTERIE)', action: 'ON', checked: false },
            { id: 'evektor-s2i4', label: 'FREINS', action: 'PIEDS SUR LES FREINS', checked: false },
            { id: 'evektor-s2i5', label: 'HORAMÈTRE', action: 'NOTÉ', checked: false },
            { id: 'evektor-s2i6', label: 'AVIONICS SWITCH + IC (INTERCOM)', action: 'OFF', checked: false },
            { id: 'evektor-s2i7', label: 'CREW ALERTING SYSTEM (EMS)', action: 'SANS ALERTE (TÉMOIN EMS NE CLIGNOTE PAS)', checked: false },
            { id: 'evektor-s2i8', label: 'VOLETS (FLAPS)', action: 'RENTRÉS', checked: false },
            { id: 'evektor-s2i9', label: 'ESSENCE', action: 'OUVERT (SUR RÉSERVOIR LE MOINS PLEIN)', checked: false },
            { id: 'evektor-s2i10', label: 'RÉCHAUFFE CARBU', action: 'SI T°EXT <15°C - TIRÉE - CHAUD', checked: false },
            { id: 'evektor-s2i11', label: 'CLÉ', action: 'EN PLACE - CONTACT SUR BOTH', checked: false },
            { id: 'evektor-s2i12', label: 'GAZ', action: 'TOUT RÉDUIT', checked: false },
            { id: 'evektor-s2i13', label: 'FUEL PUMP (POMPE ÉLECTRIQUE)', action: 'ON - PRESSION VÉRIFIÉE', checked: false },
            { id: 'evektor-s2i14', label: 'CHOKE (STARTER)', action: 'MOTEUR FROID TIRÉ COMME NÉCESSAIRE SELON T°', checked: false },
            { id: 'evektor-s2i15', label: 'BEACON', action: 'ON', checked: false },
            { id: 'evektor-s2i16', label: 'SÉCURITÉ', action: 'ABORDS DÉGAGÉS', checked: false },
            { id: 'evektor-s2i17', label: 'DÉMARREUR / START', action: 'ACTIONNÉ - MAX 10 SECONDES', checked: false },
            { id: 'evektor-s2i18', label: 'CHOKE (STARTER)', action: 'REPOUSSÉ LENTEMENT', checked: false },
            { id: 'evektor-s2i19', label: 'RÉGIME', action: '2000 RPM MAX (NE PAS DÉPASSER)', checked: false },
            { id: 'evektor-s2i20', label: 'PRESSION HUILE', action: 'VÉRIFIÉE (VERT DANS LES 10 SEC) - > 0,8 BAR', checked: false },
        ]
      },
      {
        id: 'evektor-s3',
        title: 'APRES MISE EN ROUTE',
        items: [
          { id: 'evektor-s3i1', label: 'CHRONO', action: 'PENDANT 2 MINUTES NE PAS DÉPASSER LES 2000 TR/MIN', checked: false },
          { id: 'evektor-s3i2', label: 'GEN + AUX GEN', action: 'ON - CHARGE VÉRIFIÉE', checked: false },
          { id: 'evektor-s3i3', label: 'FUEL PUMP (POMPE ÉLECTRIQUE)', action: 'OFF - PRESSION VÉRIFIÉE', checked: false },
          { id: 'evektor-s3i4', label: 'RÉCHAUFFE CARBU', action: 'POUSSÉE - FROID', checked: false },
          { id: 'evektor-s3i5', label: 'AVIONICS SWITCH + IC (INTERCOM)', action: 'ON - FRÉQUENCES & VOLUMES VÉRIFIÉS', checked: false },
          { id: 'evektor-s3i6', label: 'TRANSPONDEUR', action: 'ALT ET SUR 7000', checked: false },
          { id: 'evektor-s3i7', label: 'AFFICHAGE', action: 'EFIS (TAPES) OU SIX PACK (ROUND GAUGES)', checked: false },
          { id: 'evektor-s3i8', label: 'ALTIMÈTRE EFIS (SET FOR FIELD)', action: 'RÉGLÉ À L\'ALTITUDE PRESSION DU TERRAIN', checked: false },
          { id: 'evektor-s3i9', label: 'ALTIMÈTRE DE SECOURS', action: 'RÉGLÉ À L\'ALTITUDE PRESSION DU TERRAIN', checked: false },
          { id: 'evektor-s3i10', label: 'RÉGIME APRÈS 2 MINUTES', action: 'ENTRE 2300 ET 2500 TR/MIN MAX', checked: false },
          { id: 'evektor-s3i11', label: 'WARNING / CAUTIONING', action: 'ETEINT', checked: false },
          { id: 'evektor-s3i12', label: 'TÉMOIN EMS', action: 'ETEINT', checked: false },
          { id: 'evektor-s3i13', label: 'ATIS', action: 'NOTÉ', checked: false },
          { id: 'evektor-s3i14', label: 'TEMPÉRATURE D\'HUILE', action: '> 40°C', checked: false },
          { id: 'evektor-s3i15', label: 'COMPENSATEUR', action: 'VÉRIFIÉ - POSITION DÉCOLLAGE', checked: false },
          { id: 'evektor-s3i16', label: 'BRIEFING ROULAGE', action: 'EFFECTUÉ', checked: false },
          { id: 'evektor-s3i17', label: 'LDG LIGHT (PHARE)', action: 'ON', checked: false },
          { id: 'evektor-s3i18', label: 'CONTACT RADIO', action: 'POITIERS TOUR DE F-HNNY, BONJOUR !', checked: false },
          { id: 'evektor-s3i19', label: 'TOP CHRONO', action: 'NOTÉ', checked: false },
        ]
      },
      {
        id: 'evektor-s4',
        title: 'ROULAGE',
        items: [
            { id: 'evektor-s4i1', label: 'FREINS', action: 'ESSAYÉS', checked: false },
            { id: 'evektor-s4i2', label: 'HORIZON ARTIFICIEL', action: 'STABLE', checked: false },
            { id: 'evektor-s4i3', label: 'BILLE', action: 'DANS LE BON SENS', checked: false },
            { id: 'evektor-s4i4', label: 'AUX GEN', action: 'CLIGNOTE', checked: false },
        ]
      },
      {
        id: 'evektor-s5',
        title: 'AU POINT D\'ATTENTE',
        items: [
          { id: 'evektor-s5i1', label: 'FREINS', action: 'PIEDS SUR LES FREINS', checked: false },
          { id: 'evektor-s5i2', label: 'RÉGIME', action: 'ENTRE 2300 ET 2500 TR/MIN', checked: false },
          { id: 'evektor-s5i3', label: 'RÉSERVOIR ESSENCE', action: 'BASCULER SUR LE PLUS PLEIN', checked: false },
          { id: 'evektor-s5i4', label: 'LDG LIGHT (PHARE)', action: 'OFF', checked: false },
          { id: 'evektor-s5i5', label: 'INSTRUMENTS MOTEUR', action: 'ARC VERT (SAUF T° HUILE 50°C MINI)', checked: false },
          { id: 'evektor-s5i6', label: 'PANNEAU D\'ALARME', action: 'VÉRIFIÉ ÉTEINT (SAUF FREINS DE PARC)', checked: false },
          { id: 'evektor-s5i7', label: 'RÉCHAUFFE CARBU', action: 'POUSSÉE - FROID', checked: false },
          { id: 'evektor-s5i8', label: 'RÉGIME', action: '4000 TR/MIN', checked: false },
          { id: 'evektor-s5i9', label: 'SÉLECTION MAGNÉTOS', action: 'PERTE < 300 TR/MIN / ECART MAX R-L < 120 TR/MIN', checked: false },
          { id: 'evektor-s5i10', label: 'RECHAUFFE CARBU', action: 'ESSAI (PERTE < 100 TR/MIN)', checked: false },
          { id: 'evektor-s5i11', label: 'RALENTI', action: 'MOTEUR NE CALE PAS (MIN 1400 TR/MIN)', checked: false },
          { id: 'evektor-s5i12', label: 'RÉGIME', action: '2300 À 2500 TR/MIN', checked: false },
        ]
      },
      {
        id: 'evektor-s6',
        title: 'AVANT ALIGNEMENT',
        items: [
          { id: 'evektor-s6i1', label: 'MASTER SWITCH', action: 'ON', checked: false },
          { id: 'evektor-s6i2', label: 'GEN + AUX GEN', action: 'ON', checked: false },
          { id: 'evektor-s6i3', label: 'CONTACT MAGNÉTOS', action: 'SUR BOTH', checked: false },
          { id: 'evektor-s6i4', label: 'RÉCHAUFFE CARBU', action: 'POUSSÉE - FROID', checked: false },
          { id: 'evektor-s6i5', label: 'CHOKE (STARTER)', action: 'REPOUSSÉ (DÉCOLLAGE INTERDIT SI STARTER ENCLENCHÉ)', checked: false },
          { id: 'evektor-s6i6', label: 'HUILE', action: 'TEMP MINI 50°C - PRESSION DANS LE VERT', checked: false },
          { id: 'evektor-s6i7', label: 'FUEL PUMP (POMPE ÉLECT.)', action: 'ON - PRESSION VÉRIFIÉE', checked: false },
          { id: 'evektor-s6i8', label: 'VOLETS (FLAPS)', action: 'POSITION DÉCOL. - 1CRAN 15° - MESSAGE', checked: false },
          { id: 'evektor-s6i9', label: 'VERRIÈRE (CANOPY)', action: 'VERROUILLÉE - PAS DE MESSAGE D\'ALERTE', checked: false },
          { id: 'evektor-s6i10', label: 'HARNAIS', action: 'ATTACHÉS', checked: false },
          { id: 'evektor-s6i11', label: 'ALTIMÈTRE', action: 'AU QNH', checked: false },
          { id: 'evektor-s6i12', label: 'LDG LIGHTS (PHARE)', action: 'ON', checked: false },
          { id: 'evektor-s6i13', label: 'COMMANDES', action: 'LIBRES - PAS DE POINT DUR', checked: false },
          { id: 'evektor-s6i14', label: 'BRIEFING PANNE AU DÉCOLLAGE', action: 'EFFECTUÉ', checked: false },
          { id: 'evektor-s6i15', label: 'BRIEFING DÉPART', action: 'EFFECTUÉ', checked: false },
          { id: 'evektor-s6i16', label: 'CONTACT RADIO', action: 'PRÊT AU POINT D\'ATTENTE', checked: false },
        ]
      },
      {
        id: 'evektor-s7',
        title: 'ALIGNEMENT / DECOLLAGE',
        items: [
          { id: 'evektor-s7i1', label: 'DIRECTIONNEL ET COMPAS', action: 'VÉRIFIÉS / QHU', checked: false },
          { id: 'evektor-s7i2', label: 'PUISSANCE MINI ANNONCÉE', action: '5000 TR/MIN', checked: false },
          { id: 'evektor-s7i3', label: 'TOP CHRONO', action: 'NOTÉ', checked: false },
          { id: 'evektor-s7i4', label: 'ROTATION', action: 'VI = 50 KTS', checked: false },
          { id: 'evektor-s7i5', label: 'MONTÉE', action: 'VI = 60 KTS - BILLE CENTRÉE', checked: false },
          { id: 'evektor-s7i6', label: '300 FT / SOL', action: 'VOLETS RENTRÉS', checked: false },
          { id: 'evektor-s7i7', label: 'REGIME MAX', action: 'VI = 65 KTS', checked: false },
          { id: 'evektor-s7i8', label: '500 FT / SOL', action: 'FUEL PUMP (POMPE ÉLECTRIQUE) OFF', checked: false },
          { id: 'evektor-s7i9', label: '', action: 'PRESSION VÉRIFIÉE', checked: false },
          { id: 'evektor-s7i10', label: '', action: 'LDG LIGHT OFF', checked: false },
          { id: 'evektor-s7i11', label: 'LOW FUEL PRESSURE ALARME TOLÉRÉE', action: 'SI MOINS DE 5 SECONDES SANS CHUTE DE RPM', checked: false },
        ]
      },
      {
        id: 'evektor-s8',
        title: 'VENT ARRIERE',
        items: [
          { id: 'evektor-s8i1', label: 'RÉCHAUFFE CARBU', action: 'TIRÉE CHAUD', checked: false },
          { id: 'evektor-s8i2', label: 'FUEL PUMP (POMPE ÉLECTRIQUE)', action: 'ON', checked: false },
          { id: 'evektor-s8i3', label: 'LDG LIGHT (PHARE)', action: 'ON', checked: false },
          { id: 'evektor-s8i4', label: 'VOLETS', action: 'SORTIS 15° - 1ER CRAN (ARC BLANC)', checked: false },
        ]
      },
      {
        id: 'evektor-s9',
        title: 'FINALE',
        items: [
          { id: 'evektor-s9i1', label: 'REMISE DE GAZ', action: 'ENVISAGÉE', checked: false },
          { id: 'evektor-s9i2', label: 'VOLETS', action: 'A LA DEMANDE', checked: false },
          { id: 'evektor-s9i3', label: 'AXE - PLAN - VITESSE - CONFIGURATION', action: 'AUTORISÉ(E) OU PISTE LIBRE', checked: false },
        ]
      },
      {
        id: 'evektor-s10',
        title: 'REMISE DES GAZ',
        items: [
          { id: 'evektor-s10i1', label: 'ASSIETTE', action: '1/2 ASSIETTE DE MONTÉE - VZ POSITIF', checked: false },
          { id: 'evektor-s10i2', label: 'RÉGIME', action: 'PLEINE PUISSANCE', checked: false },
          { id: 'evektor-s10i3', label: 'RÉCHAUFFE CARBU', action: 'POUSSÉE - FROID', checked: false },
          { id: 'evektor-s10i4', label: 'VOLETS', action: 'RENTRÉS PROGRESSIVEMENT 1 CRAN', checked: false },
        ]
      },
      {
        id: 'evektor-s11',
        title: 'APRES ATTERRISSAGE - PISTE DÉGAGÉE',
        items: [
          { id: 'evektor-s11i1', label: 'RÉGIME', action: 'ENTRE 2300 ET 2500 TR/MIN', checked: false },
          { id: 'evektor-s11i2', label: 'FUEL PUMP (POMPE ÉLECTRIQUE)', action: 'OFF', checked: false },
          { id: 'evektor-s11i3', label: 'RÉCHAUFFE CARBU', action: 'POUSSÉE - FROID', checked: false },
          { id: 'evektor-s11i4', label: 'COMPENSATEUR', action: 'AU NEUTRE', checked: false },
          { id: 'evektor-s11i5', label: 'VOLETS', action: 'RENTRÉS', checked: false },
        ]
      },
      {
        id: 'evektor-s12',
        title: 'AU PARKING-ARRET MOTEUR',
        items: [
          { id: 'evektor-s12i1', label: 'RÉGIME', action: 'ENTRE 2300 ET 2500 TR/MIN', checked: false },
          { id: 'evektor-s12i2', label: 'TOP CHRONO', action: 'NOTÉ', checked: false },
          { id: 'evektor-s12i3', label: 'CONTACT RADIO', action: 'F-HNNY AU PARKING POUR QUITTER', checked: false },
          { id: 'evektor-s12i4', label: 'TRANSPONDEUR', action: 'SUR 7000 PUIS SUR OFF', checked: false },
          { id: 'evektor-s12i5', label: 'AVIONICS SWITCH + IC (INTERCOM)', action: 'OFF', checked: false },
          { id: 'evektor-s12i6', label: 'GEN + AUX GEN', action: 'OFF', checked: false },
          { id: 'evektor-s12i7', label: 'RÉGIME', action: 'RALENTI', checked: false },
          { id: 'evektor-s12i8', label: 'CONTACT MAGNÉTOS', action: 'GAUCHE MAINTENIR 2 SECONDES', checked: false },
          { id: 'evektor-s12i9', label: '', action: 'DROITE MAINTENIR 2 SECONDES', checked: false },
          { id: 'evektor-s12i10', label: '', action: 'OFF - CLEF RETIRÉE', checked: false },
          { id: 'evektor-s12i11', label: 'LDG LIGHT (PHARE)', action: 'OFF', checked: false },
          { id: 'evektor-s12i12', label: 'POS LIGHT (FEUX DE NAV)', action: 'OFF', checked: false },
          { id: 'evektor-s12i13', label: 'BEACON (ANTICOLLISION)', action: 'LAISSER SUR ON', checked: false },
          { id: 'evektor-s12i14', label: 'HORAMÈTRE', action: 'NOTÉ', checked: false },
          { id: 'evektor-s12i15', label: 'MASTER SWITCH (BATTERIE)', action: 'OFF', checked: false },
          { id: 'evektor-s12i16', label: 'BATT G3X', action: 'OFF', checked: false },
          { id: 'evektor-s12i17', label: 'CACHES', action: 'PITOT + 3 PALES + SAUMONS', checked: false },
          { id: 'evektor-s12i18', label: 'AVION', action: 'A LAVER', checked: false },
          { id: 'evektor-s12i19', label: 'DOCUMENTS', action: 'A REMPLIR', checked: false },
          { id: 'evektor-s12i20', label: 'NOTE', action: 'AU PARKING SELECTEUR CARBURANT TOUJOURS OUVERT SUR L OU SUR R. NE JAMAIS METTRE LA BARRE DE GUIDAGE SUR LA ROUE AVANT (SAUF DANS LE HANGAR)', checked: false },
        ]
      },
    ],
  }
];